name: Build Qwt

on: [push, pull_request]
jobs:
  build-qwt:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        qtver: [5.12.12, 6.5.3]
        include:
          - qtver: 6.5.3
            build_flags: -DUSE_QT6=TRUE
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Linux dependencies
        if: contains(matrix.os, 'ubuntu')
        run: sudo apt-get install libxkbcommon-x11-0 libgl1-mesa-dev mesa-common-dev libglfw3-dev libglu1-mesa-dev

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qtver }}
          dir: "${{ github.workspace }}/Qt/"
          cache: true
          cache-key-prefix: ${{ matrix.qtver }}-${{ matrix.os }}
      
      - name: Use MSVC (Windows)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure and build
        run: |
          cmake -S . ${{matrix.build_flags}} -B build
          cmake --build build
