name: Build Qwt

on: [push, pull_request]
jobs:
  ResInsight-x64:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        qtver: [5.12.12, 6.5.3]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qtver }}
          dir: "${{ github.workspace }}/Qt/"
          cache: true
          cache-key-prefix: ${{ matrix.qtver }}-${{ matrix.os }}

      - name: Install Linux dependencies
        if: "contains( matrix.os, 'ubuntu')"
        run: sudo apt-get install libxkbcommon-x11-0 libgl1-mesa-dev mesa-common-dev libglfw3-dev libglu1-mesa-dev
      
      - name: Use MSVC (Windows)
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure 5.12
        if: "contains( matrix.qtver, '5.12')"
        run: |
          cmake -S . -B build

      - name: Configure 6.5
        if: "contains( matrix.qtver, '6.5')"
        run: |
          cmake -S . -DUSE_QT6=TRUE -B build
  
      - name: Build
        run: cmake --build build
